version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "video-transcoder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vj4lgkdnzv6t"
s3_prefix = "video-transcoder"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
